import os

LOGGER_TYPE = os.environ.get('LOGGER_TYPE')
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = False
SQLALCHEMY_RECORD_QUERIES =False
SENDGRID_KEY = os.environ.get('SENDGRID_KEY')
SENDGRID_TEMPLATE_PROPOSAL_CLIENT_ID = os.environ.get('SENDGRID_TEMPLATE_PROPOSAL_CLIENT_ID')
SENDGRID_TEMPLATE_PROPOSAL_COMPANY_ID = os.environ.get('SENDGRID_TEMPLATE_PROPOSAL_COMPANY_ID')