import os

LOGGER_TYPE = os.environ.get('LOGGER_TYPE')
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True
SQLALCHEMY_RECORD_QUERIES = True